---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skuttle
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skuttle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skuttle
subjects:
  - kind: ServiceAccount
    name: skuttle
    namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skuttle
  namespace: kube-system
